"""Created Basic User Table

Revision ID: 7c8423794c8b
Revises: 
Create Date: 2023-08-15 22:25:31.773899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8423794c8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('Id', sa.String(), nullable=False),
    sa.Column('PlayerName', sa.String(), nullable=False),
    sa.Column('Gold', sa.Integer(), nullable=False),
    sa.Column('Level', sa.Integer(), nullable=False),
    sa.Column('Experience', sa.Integer(), nullable=False),
    sa.Column('Speed', sa.Integer(), nullable=False),
    sa.Column('Strength', sa.Integer(), nullable=False),
    sa.Column('CreationDate', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
